project:
  type: website
  output-dir: docs


website:
  navbar:
    left:
      - text: "Home"
        href: index.qmd

      - text: "Houston Portfolio"
        href: houston.qmd

      - text: "CV"
        href: cv/Samane.pdf

    right:
      - icon: github
        href: https://github.com/safshar2006-ui

      - icon: envelope
        href: mailto:s.afshar2006@gmail.com

format:
  html:
    theme: cosmo
    toc: false
